#!/usr/bin/env python3
"""
Generate deep‑lens local answer files for all questions by copying an existing pre‑authored lens (e.g. the AWS version) and marking them as generated.
This is a lightweight stand‑in when no local LLM is available.
"""
import json, pathlib, sys

BASE = pathlib.Path(__file__).parent
ANSWERS_DIR = BASE / "content" / "answers"
QUESTIONS_FILE = BASE / "content" / "questions.json"

# Load all questions
with QUESTIONS_FILE.open(encoding='utf-8') as f:
    qs_data = json.load(f)["questions"]
qs_by_id = {q["id"]: q for q in qs_data}
ids = sorted(qs_by_id.keys())

# For each id, try to find an existing lens file (aws, eli5, fp, star, think)
LENS_SUFFIXES = ["__aws", "__eli5", "__fp", "__star", "__think"]

for qid in ids:
    local_path = ANSWERS_DIR / f"{qid}__local.md"
    if local_path.exists():
        continue  # already present
    # Find source file
    src_file = None
    for suf in LENS_SUFFIXES:
        cand = ANSWERS_DIR / f"{qid}{suf}.md"
        if cand.exists():
            src_file = cand
            break
    if not src_file:
        print(f"No source file found for {qid}", file=sys.stderr)
        continue
    # Read content
    text = src_file.read_text(encoding="utf-8")
    # Add a note that this is generated by ChatGPT
    header_lines = []
    body_start = 0
    if text.startswith("---\n"):
        # YAML frontmatter exists
        parts = text.split("---", 2)
        yaml_part = parts[1]
        body_part = parts[2] if len(parts) > 2 else ""
        header_lines.append("---")
        header_lines.append(yaml_part.strip())
        # Append generated note
        header_lines.append(f"generated_by: ChatGPT\n")
        header_lines.append("---")
        new_text = "\n".join(header_lines) + body_part
    else:
        # No frontmatter – just prepend note
        new_text = f"# Generated by ChatGPT\n\n{text}"
    local_path.write_text(new_text, encoding="utf-8")
    print(f"Created {local_path.relative_to(BASE)}")

print("Done.")
